name: "tests-nix-linux"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@releases/v7
    - uses: cachix/cachix-action@releases/v5
      with:
        name: eigenvalue
        file: "nix/dependencies.nix"
        attributes: "dev"
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Running nix unit tests
      run: nix-test ./tests
